version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - 8082:8080
    environment:
        SPRING_PROFILES_ACTIVE: "local"
        ALLOWED_ORIGINS: "*"
        ALLOWED_METHODS: "*"
        ALLOWED_HEADERS: "*"
        EXPOSED-HEADERS: "*"
    networks:
      - default

networks:
  default:
    name: restaurant-services
    external: true