version: "3.8"
services:
  app:
    container_name: managementservice
    build:
      context: .
    ports:
      - 8082:8080
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
        SPRING_PROFILES_ACTIVE: "local"
        ALLOWED_ORIGINS: "*"
        ALLOWED_METHODS: "*"
        ALLOWED_HEADERS: "*"
        EXPOSED-HEADERS: "*"
    networks:
      - default


networks:
  default:
    name: restaurant-services
    external: true